services:
  alex-agent:
    build: .
    container_name: alex_agent
    restart: unless-stopped
    ports:
      - "3500:3500"
    environment:
      PORT: 3500
    env_file:
      - .env
    networks:
      - alex_net

networks:
  alex_net:
    external: true